# Use APT Addon to install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: java
before_install:
  - sudo apt-get -y install libc6-i386 xvfb
  - git clone https://github.com/jjYBdx4IL/misc
  - mvn install -f misc/release-parent >& log || tail -n1000 log
  - mvn install -f misc -DskipTests -DskipITs >& log || tail -n1000 log
  - git clone https://github.com/jjYBdx4IL/aspectj-utils
  - mvn install -f aspectj-utils -DskipTests -DskipITs >& log || tail -n1000 log
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
script:
  - mvn -V -B install -pl '!gwt-example/dist,!gwt-example/devel-it,!hdfs-example'
  - mvn -V -B install -DskipITs -pl gwt-example/dist -am
dist: trusty
notifications:
  email: false
jdk:
  - openjdk11

